# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'pippinpotatocorner'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-167746044-1'

menu:
- {name: 'Jazz', path: 'menu', url: 'jazz.html'}
- {name: 'Photos', path: 'menu', url: 'photos.html'}
- {name: 'All Posts', path: 'menu', url: 'allposts.html'}
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Search', path: 'menu', url: 'search.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://www.instagram.com/kindofchartreuse/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/christopher-cheung/'}
- {icon: 'envelope', link: 'mailto:cchrism0426@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
